[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
client-arena.workspace = true

axum.workspace = true
tracing.workspace = true
tokio.workspace = true
tower-http.workspace = true

tracing-subscriber.workspace = true

tower.workspace = true
hyper.workspace = true